package us.gaaoc.gajews;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Fri Mar 13 10:57:36 EDT 2009
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://GAJEWS.gaaoc.us/", name = "queuedFilings")
@XmlSeeAlso({us.gaaoc.gajews.types.ObjectFactory.class})
public interface QueuedFilings {

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getDocumentsResponse", targetNamespace = "http://GAJEWS.gaaoc.us/types/", partName = "parameters")
    @WebMethod
    public us.gaaoc.gajews.types.GetDocumentsResponse getDocuments(
        @WebParam(partName = "parameters", name = "getDocumentsRequest", targetNamespace = "http://GAJEWS.gaaoc.us/types/")
        us.gaaoc.gajews.types.GetDocumentsRequest parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getQueuedFilingsResponse", targetNamespace = "http://GAJEWS.gaaoc.us/types/", partName = "parameters")
    @WebMethod
    public us.gaaoc.gajews.types.GetQueuedFilingsResponse getQueuedFilings(
        @WebParam(partName = "parameters", name = "getQueuedFilingsRequest", targetNamespace = "http://GAJEWS.gaaoc.us/types/")
        us.gaaoc.gajews.types.GetQueuedFilingsRequest parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "importAckResponse", targetNamespace = "http://GAJEWS.gaaoc.us/types/", partName = "parameters")
    @WebMethod
    public us.gaaoc.gajews.types.ImportAckResponse importAck(
        @WebParam(partName = "parameters", name = "importAckRequest", targetNamespace = "http://GAJEWS.gaaoc.us/types/")
        us.gaaoc.gajews.types.ImportAckRequest parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "docAckResponse", targetNamespace = "http://GAJEWS.gaaoc.us/types/", partName = "parameters")
    @WebMethod
    public us.gaaoc.gajews.types.DocAckResponse docAck(
        @WebParam(partName = "parameters", name = "docAckRequest", targetNamespace = "http://GAJEWS.gaaoc.us/types/")
        us.gaaoc.gajews.types.DocAckRequest parameters
    );

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "putDocument", targetNamespace = "http://GAJEWS.gaaoc.us/types/", className = "us.gaaoc.gajews.types.PutDocument")
    @ResponseWrapper(localName = "putDocumentResponse", targetNamespace = "http://GAJEWS.gaaoc.us/types/", className = "us.gaaoc.gajews.types.PutDocumentResponse")
    @WebMethod
    public java.lang.String putDocument(
        @WebParam(name = "document", targetNamespace = "")
        us.gaaoc.gajews.types.DocumentType document
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "getCaseFilingResponse", targetNamespace = "http://GAJEWS.gaaoc.us/types/", partName = "parameters")
    @WebMethod
    public us.gaaoc.gajews.types.GetCaseFilingResponse getCaseFiling(
        @WebParam(partName = "parameters", name = "getCaseFilingRequest", targetNamespace = "http://GAJEWS.gaaoc.us/types/")
        us.gaaoc.gajews.types.GetCaseFilingRequest parameters
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "resetResponse", targetNamespace = "http://GAJEWS.gaaoc.us/types/", partName = "parameters")
    @WebMethod
    public us.gaaoc.gajews.types.ResetResponse reset(
        @WebParam(partName = "parameters", name = "resetRequest", targetNamespace = "http://GAJEWS.gaaoc.us/types/")
        us.gaaoc.gajews.types.ResetRequest parameters
    );
}
